; GTC Rega — Firmware ESP32-S3
; Build:   pio run
; Upload:  pio run -t upload
; Monitor: pio device monitor

[env:esp32-s3-devkitc-1]
platform = espressif32@^6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default_8MB.csv
board_build.flash_mode = qio

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=2

lib_deps =
    bblanchon/ArduinoJson@^7.2.0
    https://github.com/tzapu/WiFiManager.git#v2.0.17
