// Dicionário de traduções PT ↔ EN
type Dict = Record<string, string>;

const pt: Dict = {
  // Sidebar
  'sidebar.control': 'CONTROLO CENTRAL',
  'sidebar.system': 'Sistema em operação',
  'sidebar.controller': 'Controlador principal',

  // Nav
  'nav.resumo': 'Resumo',
  'nav.estado': 'Estado',
  'nav.setpoints': 'Setpoints',
  'nav.mapa': 'Mapa',
  'nav.histórico': 'Histórico',
  'nav.comandos': 'Comandos',
  'nav.alarmes': 'Alarmes',

  // Topbar
  'topbar.title': 'Sistema de Rega Automatizada',
  'topbar.settings': 'Abrir definições',

  // Page heading
  'heading.overview': 'VISÃO GERAL',
  'heading.status': 'LEITURA EM TEMPO REAL',
  'heading.connection': 'Ligação estável',

  // Overview
  'overview.systemState': 'ESTADO DO SISTEMA',
  'overview.auto': 'Automático',
  'overview.manual': 'Manual',
  'overview.actuators': 'ATUADORES',
  'overview.active': 'ativos',
  'overview.sensor': 'SENSOR',
  'overview.normal': 'Normal',
  'overview.attention': 'Atenção',
  'overview.moisture': 'Humidade do solo',
  'overview.updated': 'Atualizado agora',
  'overview.attentionOps': 'ATENÇÃO OPERACIONAL',
  'overview.nextWater': 'Próxima rega',
  'overview.scheduled': 'Agendada para amanhã às 06:30',
  'overview.system': 'SISTEMA',
  'overview.recentAlerts': 'Alertas recentes',
  'overview.location': 'LOCALIZAÇÃO',
  'overview.sensorMap': 'Mapa dos sensores',
  'overview.viewMap': 'Ver mapa completo',

  // Estado
  'estado.equipmentStatus': 'Estado dos equipamentos',
  'estado.operationMode': 'MODO DE OPERAÇÃO',
  'estado.automation': 'Automação',
  'estado.autoDesc': 'O sistema gere a rega com base nos setpoints.',
  'estado.manualDesc': 'Os atuadores aguardam comandos manuais.',
  'estado.active': 'Ativo',
  'estado.switchToManual': 'Passar para Manual',
  'estado.switchToAuto': 'Passar para Automático',
  'estado.hardware': 'HARDWARE',
  'estado.pinoutTitle': 'ESP32-S3 · Mapa de pinos GPIO',
  'estado.inputLabel': 'INPUT',
  'estado.outputLabel': 'OUTPUT → Módulo 8 Relés',
  'estado.gpio': 'GPIO',
  'estado.direction': 'Direção',
  'estado.connection': 'Ligação',
  'estado.function': 'Função',
  'estado.ready': 'Pronto',

  // Setpoints
  'setpoints.config': 'CONFIGURAÇÃO',
  'setpoints.pumpDelay': 'Delay bomba → válvulas',
  'setpoints.delayDesc': 'Delay entre ligar a bomba e abrir as válvulas',
  'setpoints.sensorMgmt': 'GESTÃO DE SENSORES',
  'setpoints.sensors': 'Sensores do projeto',
  'setpoints.activeSensors': 'sensores ativos',
  'setpoints.addSensorDesc': 'Adicione novos sensores para monitorizar mais zonas de rega',
  'setpoints.addSensor': 'Adicionar sensor',
  'setpoints.minHumidity': 'Humidade mínima desejada',
  'setpoints.waterDuration': 'Tempo de rega da válvula',
  'setpoints.tapKeyboard': 'Toque no valor para abrir o teclado numérico',

  // Mapa
  'map.realtime': 'LOCALIZAÇÃO EM TEMPO REAL',
  'map.editMode': 'Modo edição ativo',
  'map.editMap': 'Editar mapa',
  'map.pinout': 'Pinout ESP32-S3',
  'map.saveLayout': 'Guardar layout',
  'map.layoutSaved': 'Layout guardado!',
  'map.selectDrag': 'Selecionar e arrastar',
  'map.addSensor': 'Adicionar sensor',
  'map.duplicateSensor': 'Duplicar sensor',
  'map.addTerrain': 'Adicionar terreno',
  'map.curvedLines': 'Linhas curvas',
  'map.straightLines': 'Linhas retas',
  'map.resetLayout': 'Repor layout',
  'map.clearAll': 'Apagar tudo',
  'map.hintDefault': 'Ative "Editar mapa" para adicionar, mover, redimensionar ou apagar elementos',
  'map.barRename': 'Renomear',
  'map.barDuplicate': 'Duplicar',
  'map.barDelete': 'Apagar',
  'map.barViewSensor': 'Ver sensor',
  'map.barViewValve': 'Ver válvula',

  // Histórico
  'history.last24h': 'ÚLTIMAS 24 HORAS',
  'history.zoneHumidity': 'Humidade por zona',
  'history.activityLog': 'REGISTO DE ATIVIDADE',
  'history.recentEvents': 'Eventos recentes',
  'history.diagnostic': 'DIAGNÓSTICO',
  'history.errorHistory': 'Histórico de erros',

  // Comandos
  'commands.systemControl': 'CONTROLO DO SISTEMA',
  'commands.mainCommands': 'Comandos principais',
  'commands.manualControl': 'CONTROLO MANUAL',
  'commands.actuators': 'Atuadores',
  'commands.quickAction': 'AÇÃO RÁPIDA',
  'commands.systemRoutines': 'Rotinas do sistema',

  // Alarmes
  'alarms.critical': 'Críticos',
  'alarms.warnings': 'Avisos',
  'alarms.resolved': 'Resolvidos',
  'alarms.activeAlarms': 'ALARMES ATIVOS',
  'alarms.requireAttention': 'evento(s) requer(em) atenção',
  'alarms.activeDesc': 'Existem alarmes ativos que devem ser verificados.',
  'alarms.status': 'ESTADO DOS ALARMES',
  'alarms.noAlarms': 'Sem alarmes ativos',
  'alarms.noAlarmsDesc': 'Não existem falhas que impeçam o funcionamento do sistema.',
  'alarms.attention': 'Atenção',
  'alarms.allOk': 'TUDO OK',
  'alarms.requireAttentionTitle': 'Requerem atenção',
  'alarms.noActiveAlarms': 'Nenhum alarme ativo',
  'alarms.history': 'HISTÓRICO',
  'alarms.resolvedAlarms': 'Alarmes resolvidos',

  // Geral
  'general.pump': 'Bomba',
  'general.pumpOn': 'Ligada',
  'general.pumpOff': 'Desligada',
  'general.valve': 'Válvula',
  'general.valveOpen': 'Aberta',
  'general.valveClosed': 'Fechada',
  'general.sensor': 'Sensor',
  'general.online': 'Online',
  'general.offline': 'Offline',
  'general.on': 'LIGADO',
  'general.off': 'DESLIGADO',
  'general.resolved': 'Resolvido',
  'general.active': 'Ativo',
  'general.pronto': 'Pronto',

  // Settings
  'settings.title': 'Definições',
  'settings.kicker': 'PREFERÊNCIAS',
  'settings.language': 'Idioma',
  'settings.languageDesc': 'Escolha o idioma do painel.',
  'settings.account': 'Conta do operador',
  'settings.accountDesc': 'Atualize os dados de acesso ao painel.',
  'settings.username': 'Utilizador',
  'settings.password': 'Nova palavra-passe',
  'settings.passwordPlaceholder': 'Deixe vazio para manter',
  'settings.securityNote': 'Os dados de acesso ficam protegidos neste dispositivo.',
  'settings.logout': 'Terminar sessão',
  'settings.logoutDesc': 'Sair da conta de administrador.',
  'settings.logoutBtn': 'Sair',
  'settings.close': 'Fechar',
  // Login screen
  'login.welcome': 'Bem-vindo ao GTC Rega',
  'login.description': 'Sistema de rega automatizada. Introduza a senha de administrador para aceder ao painel de controlo.',
  'login.capsLock': 'Caps Lock ativo',

  'general.save': 'Guardar alterações',
  'general.saved': 'Definições guardadas',
  'general.cancel': 'Cancelar',
  'general.confirm': 'Confirmar',
  'general.close': 'Fechar',

  // Login
  'login.title': 'Acesso Restrito',
  'login.subtitle': 'Introduza a senha de administrador para continuar',
  'login.user': 'Utilizador',
  'login.password': 'Senha',
  'login.submit': 'Entrar',
  'login.error': 'Senha incorreta',

  // WiFi
  'wifi.title': 'Configuração Wi-Fi',
  'wifi.configure': 'CONFIGURAR WI-FI',
  'wifi.ssid': 'Nome da rede (SSID)',
  'wifi.password': 'Senha da rede',
  'wifi.hostname': 'Hostname do dispositivo',
  'wifi.scan': 'Procurar redes',
  'wifi.scanning': 'A procurar…',
  'wifi.connect': 'Guardar e conectar',
  'wifi.saved': 'Rede guardada!',
  'wifi.current': 'Rede atual',
  'wifi.signal': 'Sinal',
  'wifi.noNetworks': 'Nenhuma rede guardada',
  'wifi.scanResults': 'Redes encontradas',
  'wifi.delete': 'Remover',
  'wifi.deviceOffline': 'ESP32 offline — não é possível configurar Wi-Fi',
  'wifi.connectedTo': 'Conectado a',
  'wifi.ipAddress': 'Endereço IP',
};

const en: Dict = {
  'sidebar.control': 'CENTRAL CONTROL',
  'sidebar.system': 'System running',
  'sidebar.controller': 'Main controller',

  'nav.resumo': 'Overview',
  'nav.estado': 'Status',
  'nav.setpoints': 'Setpoints',
  'nav.mapa': 'Map',
  'nav.histórico': 'History',
  'nav.comandos': 'Commands',
  'nav.alarmes': 'Alarms',

  'topbar.title': 'Automated Irrigation System',
  'topbar.settings': 'Open settings',

  'heading.overview': 'OVERVIEW',
  'heading.status': 'REAL-TIME READING',
  'heading.connection': 'Stable connection',

  'overview.systemState': 'SYSTEM STATE',
  'overview.auto': 'Automatic',
  'overview.manual': 'Manual',
  'overview.actuators': 'ACTUATORS',
  'overview.active': 'active',
  'overview.sensor': 'SENSOR',
  'overview.normal': 'Normal',
  'overview.attention': 'Attention',
  'overview.moisture': 'Soil moisture',
  'overview.updated': 'Updated now',
  'overview.attentionOps': 'OPERATIONAL ATTENTION',
  'overview.nextWater': 'Next watering',
  'overview.scheduled': 'Scheduled for tomorrow at 06:30',
  'overview.system': 'SYSTEM',
  'overview.recentAlerts': 'Recent alerts',
  'overview.location': 'LOCATION',
  'overview.sensorMap': 'Sensor map',
  'overview.viewMap': 'View full map',

  'estado.equipmentStatus': 'Equipment status',
  'estado.operationMode': 'OPERATION MODE',
  'estado.automation': 'Automation',
  'estado.autoDesc': 'The system manages irrigation based on setpoints.',
  'estado.manualDesc': 'Actuators are waiting for manual commands.',
  'estado.active': 'Active',
  'estado.switchToManual': 'Switch to Manual',
  'estado.switchToAuto': 'Switch to Automatic',
  'estado.hardware': 'HARDWARE',
  'estado.pinoutTitle': 'ESP32-S3 · GPIO Pin Map',
  'estado.inputLabel': 'INPUT',
  'estado.outputLabel': 'OUTPUT → 8-Relay Module',
  'estado.gpio': 'GPIO',
  'estado.direction': 'Direction',
  'estado.connection': 'Connection',
  'estado.function': 'Function',
  'estado.ready': 'Ready',

  'setpoints.config': 'CONFIGURATION',
  'setpoints.pumpDelay': 'Pump → valve delay',
  'setpoints.delayDesc': 'Delay between starting the pump and opening valves',
  'setpoints.sensorMgmt': 'SENSOR MANAGEMENT',
  'setpoints.sensors': 'Project sensors',
  'setpoints.activeSensors': 'active sensors',
  'setpoints.addSensorDesc': 'Add new sensors to monitor more irrigation zones',
  'setpoints.addSensor': 'Add sensor',
  'setpoints.minHumidity': 'Minimum desired humidity',
  'setpoints.waterDuration': 'Valve watering duration',
  'setpoints.tapKeyboard': 'Tap the value to open the numeric keypad',

  'map.realtime': 'REAL-TIME LOCATION',
  'map.editMode': 'Edit mode active',
  'map.editMap': 'Edit map',
  'map.pinout': 'ESP32-S3 Pinout',
  'map.saveLayout': 'Save layout',
  'map.layoutSaved': 'Layout saved!',
  'map.selectDrag': 'Select and drag',
  'map.addSensor': 'Add sensor',
  'map.duplicateSensor': 'Duplicate sensor',
  'map.addTerrain': 'Add terrain',
  'map.curvedLines': 'Curved lines',
  'map.straightLines': 'Straight lines',
  'map.resetLayout': 'Reset layout',
  'map.clearAll': 'Clear all',
  'map.hintDefault': 'Enable "Edit map" to add, move, resize or delete elements',
  'map.barRename': 'Rename',
  'map.barDuplicate': 'Duplicate',
  'map.barDelete': 'Delete',
  'map.barViewSensor': 'View sensor',
  'map.barViewValve': 'View valve',

  'history.last24h': 'LAST 24 HOURS',
  'history.zoneHumidity': 'Humidity by zone',
  'history.activityLog': 'ACTIVITY LOG',
  'history.recentEvents': 'Recent events',
  'history.diagnostic': 'DIAGNOSTICS',
  'history.errorHistory': 'Error history',

  'commands.systemControl': 'SYSTEM CONTROL',
  'commands.mainCommands': 'Main commands',
  'commands.manualControl': 'MANUAL CONTROL',
  'commands.actuators': 'Actuators',
  'commands.quickAction': 'QUICK ACTION',
  'commands.systemRoutines': 'System routines',

  'alarms.critical': 'Critical',
  'alarms.warnings': 'Warnings',
  'alarms.resolved': 'Resolved',
  'alarms.activeAlarms': 'ACTIVE ALARMS',
  'alarms.requireAttention': 'event(s) require attention',
  'alarms.activeDesc': 'There are active alarms that should be checked.',
  'alarms.status': 'ALARM STATUS',
  'alarms.noAlarms': 'No active alarms',
  'alarms.noAlarmsDesc': 'There are no faults preventing system operation.',
  'alarms.attention': 'Attention',
  'alarms.allOk': 'ALL OK',
  'alarms.requireAttentionTitle': 'Require attention',
  'alarms.noActiveAlarms': 'No active alarms',
  'alarms.history': 'HISTORY',
  'alarms.resolvedAlarms': 'Resolved alarms',

  'general.pump': 'Pump',
  'general.pumpOn': 'On',
  'general.pumpOff': 'Off',
  'general.valve': 'Valve',
  'general.valveOpen': 'Open',
  'general.valveClosed': 'Closed',
  'general.sensor': 'Sensor',
  'general.online': 'Online',
  'general.offline': 'Offline',
  'general.on': 'ON',
  'general.off': 'OFF',
  'general.resolved': 'Resolved',
  'general.active': 'Active',
  'general.pronto': 'Ready',

  // Settings
  'settings.title': 'Settings',
  'settings.kicker': 'PREFERENCES',
  'settings.language': 'Language',
  'settings.languageDesc': 'Choose the dashboard language.',
  'settings.account': 'Operator Account',
  'settings.accountDesc': 'Update the dashboard access credentials.',
  'settings.username': 'Username',
  'settings.password': 'New password',
  'settings.passwordPlaceholder': 'Leave blank to keep',
  'settings.securityNote': 'Access credentials are protected on this device.',
  'settings.logout': 'Logout',
  'settings.logoutDesc': 'Sign out of the administrator account.',
  'settings.logoutBtn': 'Sign out',
  'settings.close': 'Close',
  // Login screen
  'login.welcome': 'Welcome to GTC Rega',
  'login.description': 'Automated irrigation system. Enter the administrator password to access the control panel.',
  'login.capsLock': 'Caps Lock is on',

  'general.save': 'Save changes',
  'general.saved': 'Settings saved',
  'general.cancel': 'Cancel',
  'general.confirm': 'Confirm',
  'general.close': 'Close',

  'login.title': 'Restricted Access',
  'login.subtitle': 'Enter the admin password to continue',
  'login.user': 'Username',
  'login.password': 'Password',
  'login.submit': 'Login',
  'login.error': 'Incorrect password',

  // WiFi
  'wifi.title': 'Wi-Fi Configuration',
  'wifi.configure': 'CONFIGURE WI-FI',
  'wifi.ssid': 'Network name (SSID)',
  'wifi.password': 'Network password',
  'wifi.hostname': 'Device hostname',
  'wifi.scan': 'Scan networks',
  'wifi.scanning': 'Scanning…',
  'wifi.connect': 'Save and connect',
  'wifi.saved': 'Network saved!',
  'wifi.current': 'Current network',
  'wifi.signal': 'Signal',
  'wifi.noNetworks': 'No saved networks',
  'wifi.scanResults': 'Networks found',
  'wifi.delete': 'Remove',
  'wifi.deviceOffline': 'ESP32 offline — cannot configure Wi-Fi',
  'wifi.connectedTo': 'Connected to',
  'wifi.ipAddress': 'IP address',
};

export function t(key: string, lang: 'PT' | 'EN'): string {
  const dict = lang === 'EN' ? en : pt;
  return dict[key] ?? key;
}
